name: Tests

on:
  push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Cairo toolchain
        uses: software-mansion/setup-scarb@v1
        with:
            scarb-version: "0.6.2"

      - run: "echo $PATH"

      - run: "ls -la /opt/hostedtoolcache/scarb/0.6.2/x86_64-unknown-linux-gnu/bin"

      - name: Run tests
        run: scarb test
